# -*- coding: utf-8 -*-
"""First_AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V_J7itR46w6BUECR_03NruLzEHfLjw-P
"""

# Google Drive
from google.colab import drive
drive.mount('/content/drive')

#  Import libraries
import pandas as pd
from sklearn.linear_model import LinearRegression

#Load CSV from Drive
df = pd.read_csv("/content/drive/MyDrive/scoreData.csv")
csv_path = "/content/drive/MyDrive/scoreData.csv"
# Separate features (X) and target (y) -- Refrencing data from file
X = df[["studied", "slept"]].values # 2d array
y = df["score"].values

# Train model
model = LinearRegression()
model.fit(X, y)


# Ask user for new input
study = float(input("Enter hours studied: "))
sleep = float(input("Enter hours slept: "))
actual_score = float(input("Enter actual test score: "))



save = str(input("Do you want to save this data (for training)? (yes/no)"))
if save == "yes":

  # Add to CSV for training
    new_row = pd.DataFrame({
    "studied": [study],
    "slept": [sleep],
    "score": [actual_score]
})
    df = pd.concat([df, new_row], ignore_index=True)
    df.to_csv(csv_path, index=False)
    print("Saved! Your AI will learn from this input next time.")

  # Train model on updated data
    X = df[["studied", "slept"]].values
    y = df["score"].values
    model.fit(X, y)

# Predict for the same input
predicted_score = model.predict([[study, sleep]])[0]
# boundaries
if predicted_score > 100:
  predicted_score = 100
elif predicted_score < 0:
  predicted_score = 0


print(f"Predicted score for these inputs: {predicted_score:.1f}")