# -*- coding: utf-8 -*-
"""First_AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V_J7itR46w6BUECR_03NruLzEHfLjw-P
"""

from google.colab import drive
drive.mount('/content/drive')

affirmative = "/content/drive/MyDrive/affirmative.csv"
negative = "/content/drive/MyDrive/negative.csv"

import pandas as pd

class Answer:

    @staticmethod
    def determine_answer(reply):
        reply = reply.lower()

        # Load lists
        a = pd.read_csv(affirmative, header=None)[0].str.lower().tolist()
        n = pd.read_csv(negative, header=None)[0].str.lower().tolist()

        if reply in a:
            return 1
        if reply in n:
            return 0

        # Unknown
        follow_up = input(f"I didn't understand '{reply}'. Does it mean yes? (yes/no): ").lower()

        if follow_up in ["yes","y","yeah"]:
            pd.DataFrame([reply]).to_csv(affirmative, mode='a', header=False, index=False)
            return 1

        pd.DataFrame([reply]).to_csv(negative, mode='a', header=False, index=False)
        return 0

import random

class Greeting:
    @staticmethod
    def chooseGreeting():
        greeting = ["hi", "hello!", "hey"]
        return random.choice(greeting)

import pandas as pd
from sklearn.linear_model import LinearRegression

class Model:

    def __init__(self):
        self.csv_path = "/content/drive/MyDrive/scoreData.csv"
        self.df = pd.read_csv(self.csv_path)

        if "homework" not in self.df.columns:
            self.df["homework"] = -1

        X = self.df[['studied','slept','homework']]
        y = self.df['score']

        self.model = LinearRegression()
        self.model.fit(X, y)

    def run(self):
        print(Greeting.chooseGreeting())

        study = float(input("Enter hours studied: "))
        sleep = float(input("Enter hours slept: "))
        hw_input = input("Did you do homework well? (yes/no): ")

        answer = Answer.determine_answer(hw_input)
        homework = 1 if answer == 1 else 0

        predicted = self.model.predict([[study, sleep, homework]])[0]
        predicted = max(0, min(predicted, 100))

        print(f"My Predicted score: {predicted:.1f}")

        actual = float(input("What was your actual score? "))

        save = input("Save to training data? (yes/no): ").lower()

        if save == "yes":
            new_row = pd.DataFrame({
                "studied":[study],
                "slept":[sleep],
                "homework":[homework],
                "score":[actual]
            })

            self.df = pd.concat([self.df, new_row], ignore_index=True)
            self.df.to_csv(self.csv_path, index=False)
  # MAIN PROGRAM
if __name__ == "__main__":
    m = Model()
    m.run()

